[hp]
lr = 1e-3
warmup = 50000
num_epochs = 10
epoch_size = 190_000
img_logging_rate = 20000
masking = true
masking_factor = 0.9
masking_size = 4
artifact = "none"


[ema]
enabled = false
beta = 0.9
interval = 1000
start = 20000

[vqvae]
h_dim = 128
res_h_dim = 64
n_res_layers = 4
n_embeddings = 1024
stacks = 2
embedding_dim = 64
beta = 0.5

[tsvae]
in_dim = 64
h_dim = 128
res_h_dim = 64
n_res_layers = 4
stacks = 3
e_dim = 64
heads = 8

[compile]
fullgraph = true
mode = "max-autotune"

[data]
flist = "/cluster/research-groups/wehrwein/webcam/rane/fullpairs/filelist.txt"
dir = "/cluster/research-groups/wehrwein/webcam/rane/fullpairs/"
periodic = true
batch_size = 32
num_threads = 2
fill = 5000
prefetch = 4
shuffle = true

[val_data]
to_diff = false
data_dir = "/cluster/research-groups/wehrwein/webcam/geiranger/validation_frames_random/"
input_size = [256, 256]
fps = 30
offset_seconds = 17251202
batch_size = 6
num_workers = 0
