[hp]
warmup = 50000
num_epochs = 10
epoch_size = 190_000
img_logging_rate = 20000
masking = true
masking_factor = 0.9
masking_size = 4
artifact = "none"

[optimizer]
lr = 1e-3
weight_decay = 0.3
T_alpha_beta3 = 250_000
betas = [0.9, 0.999, 0.9999]

[ema]
enabled = false
beta = 0.9
interval = 1000
start = 20000

[outer]
h_dim = 128
res_h_dim = 64
n_res_layers = 4
n_embeddings = 1024
stacks = 2
embedding_dim = 8
beta = 0.25

[inner]
in_dim = 128
h_dim = 128
res_h_dim = 64
n_res_layers = 4
stacks = 4
e_dim = 10
heads = 8
n_embeddings = 1024
embedding_dim = 32
beta = 0.25

[compile]
fullgraph = true
mode = "max-autotune"

[data]
flist = "/cluster/research-groups/wehrwein/webcam/geiranger/allframes/filelist.txt"
dir = "/cluster/research-groups/wehrwein/webcam/geiranger/allframes/"
periodic = true
batch_size = 32
num_threads = 2
fill = 5000
prefetch = 4
shuffle = true

[val_data]
flist = "/cluster/research-groups/wehrwein/webcam/geiranger/valframes/filelist.txt"
dir = "/cluster/research-groups/wehrwein/webcam/geiranger/valframes/"
periodic = true
batch_size = 32
num_threads = 2
fill = 5000
prefetch = 4
shuffle = true
