[hp]
lr = 1e-3
num_epochs = 5
epoch_size = 10000

[model]
depth = 4
down_layers = ["ResDown", 'AttnDown', 'AttnDown']
up_layers = ['AttnUp', 'AttnUp', 'ResUp']
in_dims = 3
h_dims = 512
out_dims = 3
kernel_size = 3
padding = 1
e_dims = 64

[compile]
fullgraph = true
mode = "max-autotune"

[data]
filelist = "/scratch_ssd/research-groups/wehrwein/diffusion_frames/4hrs/filelist.txt"
periodic = true
batch_size = 12
num_threads = 4
fill = 5000
prefetch = 4
shuffle = true


[val_data]
to_diff = false
data_dir = "/cluster/research-groups/wehrwein/webcam/geiranger/validation_frames_random/"
input_size = [256, 256]
fps = 30
offset_seconds = 17251202
batch_size = 6
num_workers = 0
