[hp]
lr = 1e-3
warmup = 50000
num_epochs = 10
epoch_size = 200000
img_logging_rate = 20000
masking = true
masking_factor = 0.9
masking_size = 4

[ema]
enabled = false
beta = 0.99
interval = 250000
start = 250000

[unet]
depth = 4
down_layers = ['AttnDown', "AttnDown", 'AttnDown']
up_layers = ['AttnUp', 'AttnUp', 'AttnUp']
in_dims = 64
h_dims = 512
out_dims = 64
kernel_size = 3
padding = 1
e_dims = 64
heads = 8

[vqvae]
h_dim = 128
res_h_dim = 64
n_res_layers = 4
n_embeddings = 1024
stacks = 2
embedding_dim = 64
beta = 0.6

[compile]
fullgraph = true
mode = "max-autotune"

[data]
flist = "/cluster/research-groups/wehrwein/webcam/geiranger/allframes/filelist.txt"
dir = "/cluster/research-groups/wehrwein/webcam/geiranger/allframes/"
periodic = true
batch_size = 32
num_threads = 1
fill = 5000
prefetch = 4
shuffle = true

[val_data]
to_diff = false
data_dir = "/cluster/research-groups/wehrwein/webcam/geiranger/validation_frames_random/"
input_size = [256, 256]
fps = 30
offset_seconds = 17251202
batch_size = 6
num_workers = 0
