[hp]
lr = 1e-3
num_epochs = 5
epoch_size = 200000
img_logging_rate = 15000

[ema]
beta = 0.25
interval = 1000

[unet]
depth = 4
down_layers = ['AttnDown', "AttnDown", 'AttnDown']
up_layers = ['AttnUp', 'AttnUp', 'AttnUp']
in_dims = 64
h_dims = 256
out_dims = 64
kernel_size = 5
padding = 2
e_dims = 64
heads = 8

[vqvae]
h_dim = 128
res_h_dim = 64
n_res_layers = 4
n_embeddings = 1024
embedding_dim = 64
beta = 0.5

[compile]
fullgraph = true
mode = "reduce-overhead"

[data]
dir = "/scratch_ssd/research-groups/wehrwein/diffusion_frames/random/"
periodic = true
batch_size = 32
num_threads = 4
fill = 5000
prefetch = 4
shuffle = true

[val_data]
to_diff = false
data_dir = "/cluster/research-groups/wehrwein/webcam/geiranger/validation_frames_random/"
input_size = [256, 256]
fps = 30
offset_seconds = 17251202
batch_size = 6
num_workers = 0
